Load File into python and clean headers

In [1]:
import pandas as pd

col_name = ['Date','Close','High','Low','Open','Volume']


jkh = pd.read_csv('E:/DATA ANALYSIS/CSE_Macro_Project/raw_data/JKH_stock_prices_2020_2026.csv',skiprows=3,names=col_name)
comb = pd.read_csv('E:/DATA ANALYSIS/CSE_Macro_Project/raw_data/COMB_stock_prices_2020_2026.csv',skiprows=3,names=col_name)
dial = pd.read_csv('E:/DATA ANALYSIS/CSE_Macro_Project/raw_data/DIAL_stock_prices_2020_2026.csv',skiprows=3,names=col_name)
lolc = pd.read_csv('E:/DATA ANALYSIS/CSE_Macro_Project/raw_data/LOLC_stock_prices_2020_2026.csv',skiprows=3,names=col_name)
macro = pd.read_csv('E:/DATA ANALYSIS/CSE_Macro_Project/raw_data/CBSL_macro_data_clean.csv')

In [2]:
print("JKH columns:", list(jkh.columns))
print()
print("Macro columns:", list(macro.columns))
print()
print(jkh.head())
print(jkh.dtypes)

JKH columns: ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

Macro columns: ['Month', 'CCPI_Index', 'CCPI_YoY_Percent', 'Avg_Weighted_Lending_Rate', 'USD_LKR_Exchange_Rate']

         Date       Close        High         Low        Open  Volume
0  2020-01-01  163.324234  163.324234  163.324234  163.324234       0
1  2020-01-02  159.718658  162.739579  159.328869  162.739579   85347
2  2020-01-03  159.913528  160.790562  159.036480  159.036480   19847
3  2020-01-06  157.964554  162.739540  157.379855  162.739540  100582
4  2020-01-07  158.744141  160.790572  157.964562  160.790572  433671
Date          str
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

Clean date format for analysis

In [3]:
def clean_and_monthly(df,name):
    df = df.copy()
    df['Date'] = pd.to_datetime(df['Date']) # string -> datetime convert
    df = df.sort_values('Date')
    df['Month'] = df['Date'].dt.to_period('M').dt.to_timestamp()

    monthly = df.groupby('Month').agg(
        avg_close = ('Close','mean'),
        max_close = ('Close','max'),
        min_close = ('Close','min'),
        avg_volume = ('Volume','mean')
    ).reset_index()
    monthly.columns = ['Month'] + [f'{name}_{c}' for c in monthly.columns[1:]]
    return monthly

call the functions

In [4]:
jkh_m = clean_and_monthly(jkh,'JKH')
comb_m = clean_and_monthly(comb,'COMB')
dial_m = clean_and_monthly(dial,'DIAL')
lolc_m = clean_and_monthly(lolc,'LOLC')

print(jkh_m.head())
print(jkh_m.shape)

       Month  JKH_avg_close  JKH_max_close  JKH_min_close  JKH_avg_volume
0 2020-01-01     159.722870     163.324234     156.405365    2.534810e+05
1 2020-02-01     151.939384     157.769623     142.407242    2.548750e+05
2 2020-03-01     125.147252     146.308823     112.560272    7.167314e+05
3 2020-04-01     112.560272     112.560272     112.560272    5.059039e+05
4 2020-05-01     101.310739     112.950424      78.519073    1.747143e+06
(81, 5)

merge to macro

In [5]:
macro['Month'] = pd.to_datetime(macro['Month'])

final = macro.merge(jkh_m, on='Month', how='left')\
        .merge(comb_m, on='Month', how='left')\
        .merge(dial_m, on='Month', how='left')\
        .merge(lolc_m, on='Month', how='left')
print(final.shape)
final.head()

(81, 21)

,Month,CCPI_Index,CCPI_YoY_Percent,Avg_Weighted_Lending_Rate,USD_LKR_Exchange_Rate,JKH_avg_close,JKH_max_close,JKH_min_close,JKH_avg_volume,COMB_avg_close,...,COMB_min_close,COMB_avg_volume,DIAL_avg_close,DIAL_max_close,DIAL_min_close,DIAL_avg_volume,LOLC_avg_close,LOLC_max_close,LOLC_min_close,LOLC_avg_volume
0,2020-01-01,NaN,NaN,13.47,181.40,159.722870,163.324234,156.405365,2.534810e+05,61.098530,...,59.319828,6.635465e+05,7.569543,7.814486,7.451022,4.269183e+05,160.978261,177.500000,152.000000,109574.652174
1,2020-02-01,NaN,NaN,13.36,181.56,151.939384,157.769623,142.407242,2.548750e+05,60.257939,...,58.183857,5.503390e+05,7.566119,7.753908,7.148135,3.559112e+05,144.005000,152.100006,129.899994,22372.650000
2,2020-03-01,NaN,NaN,13.22,185.06,125.147252,146.308823,112.560272,7.167314e+05,48.508199,...,40.898827,1.173906e+06,5.909051,7.148135,5.149080,1.294076e+06,107.509092,134.699997,90.800003,92861.772727
3,2020-04-01,NaN,NaN,13.08,193.09,112.560272,112.560272,112.560272,5.059039e+05,40.898827,...,40.898827,1.326000e+06,5.149080,5.149080,5.149080,1.507273e+06,90.800003,90.800003,90.800003,95910.545455
4,2020-05-01,NaN,NaN,12.96,187.87,101.310739,112.950424,78.519073,1.747143e+06,41.119184,...,34.093700,5.369339e+06,5.489468,6.421206,4.785616,2.692823e+06,100.833334,115.000000,88.199997,121681.190476

Core Period Filter  (2022-2024)

In [9]:
core = final[(final['Month'] >= pd.Timestamp('2022-01-01'))  & (final['Month'] <= pd.Timestamp('2024-02-29'))].copy()

print(core.shape)
print(core.isna().sum())

(26, 21)
Month                         0
CCPI_Index                    0
CCPI_YoY_Percent             13
Avg_Weighted_Lending_Rate     0
USD_LKR_Exchange_Rate         0
JKH_avg_close                 0
JKH_max_close                 0
JKH_min_close                 0
JKH_avg_volume                0
COMB_avg_close                0
COMB_max_close                0
COMB_min_close                0
COMB_avg_volume               0
DIAL_avg_close                0
DIAL_max_close                0
DIAL_min_close                0
DIAL_avg_volume               0
LOLC_avg_close                0
LOLC_max_close                0
LOLC_min_close                0
LOLC_avg_volume               0
dtype: int64

connect postgresql database

In [11]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:admin1234@localhost:5432/cse_analysis')

try:
    conn_test = engine.connect()
    print('Sucessful')
    conn_test.close()
except Exception as e:
    print('Unsucssful')

Sucessful

import table to SQL

In [13]:
core.to_sql('master_data', engine, if_exists='replace', index=False)
core.to_sql('full_data', engine,if_exists='replace',index=False )

print('Table create successfull')

check = pd.read_sql("SELECT * FROM master_data LIMIT 5;", engine)
check

Table create successfull

,Month,CCPI_Index,CCPI_YoY_Percent,Avg_Weighted_Lending_Rate,USD_LKR_Exchange_Rate,JKH_avg_close,JKH_max_close,JKH_min_close,JKH_avg_volume,COMB_avg_close,...,COMB_min_close,COMB_avg_volume,DIAL_avg_close,DIAL_max_close,DIAL_min_close,DIAL_avg_volume,LOLC_avg_close,LOLC_max_close,LOLC_min_close,LOLC_avg_volume
0,2022-01-01,124.3,None,10.12,201.46,155.111426,160.008820,146.084396,527124.380952,61.096332,...,59.538246,355821.761905,7.598791,8.066114,7.192284,2.978242e+06,1321.166667,1443.25,1176.00,169313.000000
1,2022-02-01,125.8,None,10.13,201.74,151.289076,156.344513,141.731934,341702.500000,60.277803,...,58.940620,335771.150000,7.588869,7.931679,7.326720,3.017712e+06,1087.825000,1193.50,828.75,128529.550000
2,2022-03-01,129.7,None,10.35,255.81,146.916747,153.461502,138.066452,537646.086957,57.943424,...,51.842155,232249.217391,7.469922,7.864460,6.721761,1.729504e+06,819.902174,994.75,597.50,138000.260870
3,2022-04-01,142.1,None,11.31,319.44,134.121702,145.641785,115.584862,244178.571429,46.711881,...,41.341431,460711.380952,6.376071,6.654543,5.982368,9.858220e+05,397.571429,489.50,269.00,150440.190476
4,2022-05-01,153.6,None,13.46,358.94,124.870740,132.201706,120.227798,175147.590909,43.442329,...,41.341431,432801.363636,6.342898,6.721761,6.049585,5.528245e+05,524.829545,631.50,415.50,94916.818182